# This is a basic workflow to help you get started with Actions

name: sync2gitee

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Github Branch Gitee
      uses: shanghaobo/github-branch-gitee@v1.0.0
      with:
        github_repo: ACL4SSR/ACL4SSR
        github_branch: master
        gitee_repo: Machikado/rules
        gitee_branch: test
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}
